/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalonsRouteImport } from './routes/salons'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiAnalysisRouteImport } from './routes/ai-analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StylistsIdRouteImport } from './routes/stylists.$id'
import { Route as SalonsIdRouteImport } from './routes/salons.$id'

const SalonsRoute = SalonsRouteImport.update({
  id: '/salons',
  path: '/salons',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalysisRoute = AiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StylistsIdRoute = StylistsIdRouteImport.update({
  id: '/stylists/$id',
  path: '/stylists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsIdRoute = SalonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/gallery': typeof GalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/packages': typeof PackagesRoute
  '/planner': typeof PlannerRoute
  '/salons': typeof SalonsRouteWithChildren
  '/salons/$id': typeof SalonsIdRoute
  '/stylists/$id': typeof StylistsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/gallery': typeof GalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/packages': typeof PackagesRoute
  '/planner': typeof PlannerRoute
  '/salons': typeof SalonsRouteWithChildren
  '/salons/$id': typeof SalonsIdRoute
  '/stylists/$id': typeof StylistsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/gallery': typeof GalleryRoute
  '/onboarding': typeof OnboardingRoute
  '/packages': typeof PackagesRoute
  '/planner': typeof PlannerRoute
  '/salons': typeof SalonsRouteWithChildren
  '/salons/$id': typeof SalonsIdRoute
  '/stylists/$id': typeof StylistsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analysis'
    | '/auth'
    | '/discover'
    | '/explore'
    | '/gallery'
    | '/onboarding'
    | '/packages'
    | '/planner'
    | '/salons'
    | '/salons/$id'
    | '/stylists/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-analysis'
    | '/auth'
    | '/discover'
    | '/explore'
    | '/gallery'
    | '/onboarding'
    | '/packages'
    | '/planner'
    | '/salons'
    | '/salons/$id'
    | '/stylists/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-analysis'
    | '/auth'
    | '/discover'
    | '/explore'
    | '/gallery'
    | '/onboarding'
    | '/packages'
    | '/planner'
    | '/salons'
    | '/salons/$id'
    | '/stylists/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAnalysisRoute: typeof AiAnalysisRoute
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  ExploreRoute: typeof ExploreRoute
  GalleryRoute: typeof GalleryRoute
  OnboardingRoute: typeof OnboardingRoute
  PackagesRoute: typeof PackagesRoute
  PlannerRoute: typeof PlannerRoute
  SalonsRoute: typeof SalonsRouteWithChildren
  StylistsIdRoute: typeof StylistsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salons': {
      id: '/salons'
      path: '/salons'
      fullPath: '/salons'
      preLoaderRoute: typeof SalonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analysis': {
      id: '/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/ai-analysis'
      preLoaderRoute: typeof AiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylists/$id': {
      id: '/stylists/$id'
      path: '/stylists/$id'
      fullPath: '/stylists/$id'
      preLoaderRoute: typeof StylistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons/$id': {
      id: '/salons/$id'
      path: '/$id'
      fullPath: '/salons/$id'
      preLoaderRoute: typeof SalonsIdRouteImport
      parentRoute: typeof SalonsRoute
    }
  }
}

interface SalonsRouteChildren {
  SalonsIdRoute: typeof SalonsIdRoute
}

const SalonsRouteChildren: SalonsRouteChildren = {
  SalonsIdRoute: SalonsIdRoute,
}

const SalonsRouteWithChildren =
  SalonsRoute._addFileChildren(SalonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAnalysisRoute: AiAnalysisRoute,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  ExploreRoute: ExploreRoute,
  GalleryRoute: GalleryRoute,
  OnboardingRoute: OnboardingRoute,
  PackagesRoute: PackagesRoute,
  PlannerRoute: PlannerRoute,
  SalonsRoute: SalonsRouteWithChildren,
  StylistsIdRoute: StylistsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
